Language.create(name: 'A# .NET', url:'http://en.wikipedia.org/wiki/A_Sharp_(.NET)')
Language.create(name: 'A# (Axiom)', url:'http://en.wikipedia.org/wiki/A_Sharp_(Axiom)')
Language.create(name: 'A-0 System', url:'http://en.wikipedia.org/wiki/A-0_System')
Language.create(name: 'A+', url:'http://en.wikipedia.org/wiki/A%2B_(programming_language)')
Language.create(name: 'A++', url:'http://en.wikipedia.org/wiki/A%2B%2B')
Language.create(name: 'ABAP', url:'http://en.wikipedia.org/wiki/ABAP')
Language.create(name: 'ABC', url:'http://en.wikipedia.org/wiki/ABC_(programming_language)')
Language.create(name: 'ABC ALGOL', url:'http://en.wikipedia.org/wiki/ABC_ALGOL')
Language.create(name: 'ABLE', url:'http://en.wikipedia.org/wiki/ABLE_(programming_language)')
Language.create(name: 'ABSET', url:'http://en.wikipedia.org/wiki/ABSET')
Language.create(name: 'ABSYS', url:'http://en.wikipedia.org/wiki/ABSYS')
Language.create(name: 'ACC', url:'http://en.wikipedia.org/wiki/ACC_(programming_language)')
Language.create(name: 'Accent', url:'http://en.wikipedia.org/wiki/Accent_(programming_language)')
Language.create(name: 'Ace DASL', url:'http://en.wikipedia.org/wiki/Distributed_Application_Specification_Language')
Language.create(name: 'ACL2', url:'http://en.wikipedia.org/wiki/ACL2')
Language.create(name: 'ACT-III', url:'http://en.wikipedia.org/wiki/LGP-30#ACT-III_programming_language')
Language.create(name: 'Action!', url:'http://en.wikipedia.org/wiki/Action!_(programming_language)')
Language.create(name: 'ActionScript', url:'http://en.wikipedia.org/wiki/ActionScript')
Language.create(name: 'Ada', url:'http://en.wikipedia.org/wiki/Ada_(programming_language)')
Language.create(name: 'Adenine', url:'http://en.wikipedia.org/wiki/Adenine_(programming_language)')
Language.create(name: 'Agda', url:'http://en.wikipedia.org/wiki/Agda_(theorem_prover)')
Language.create(name: 'Agilent VEE', url:'http://en.wikipedia.org/wiki/Agilent_VEE')
Language.create(name: 'Agora', url:'http://en.wikipedia.org/wiki/Agora_(programming_language)')
Language.create(name: 'AIMMS', url:'http://en.wikipedia.org/wiki/AIMMS')
Language.create(name: 'Alef', url:'http://en.wikipedia.org/wiki/Alef_(programming_language)')
Language.create(name: 'ALF', url:'http://en.wikipedia.org/wiki/Algebraic_Logic_Functional_programming_language')
Language.create(name: 'ALGOL 58', url:'http://en.wikipedia.org/wiki/ALGOL_58')
Language.create(name: 'ALGOL 60', url:'http://en.wikipedia.org/wiki/ALGOL_60')
Language.create(name: 'ALGOL 68', url:'http://en.wikipedia.org/wiki/ALGOL_68')
Language.create(name: 'ALGOL W', url:'http://en.wikipedia.org/wiki/ALGOL_W')
Language.create(name: 'Alice', url:'http://en.wikipedia.org/wiki/Alice_(programming_language)')
Language.create(name: 'Alma-0', url:'http://en.wikipedia.org/wiki/Alma-0')
Language.create(name: 'AmbientTalk', url:'http://en.wikipedia.org/wiki/AmbientTalk')
Language.create(name: 'Amiga E', url:'http://en.wikipedia.org/wiki/Amiga_E')
Language.create(name: 'AMOS', url:'http://en.wikipedia.org/wiki/AMOS_(programming_language)')
Language.create(name: 'AMPL', url:'http://en.wikipedia.org/wiki/AMPL')
Language.create(name: 'Apex', url:'http://en.wikipedia.org/wiki/Salesforce.com#Apex')
Language.create(name: 'APL', url:'http://en.wikipedia.org/wiki/APL_(programming_language)')
Language.create(name: 'App Inventor for Android’s visual block language', url:'http://en.wikipedia.org/wiki/App_Inventor_for_Android_(programming_language)')
Language.create(name: 'AppleScript', url:'http://en.wikipedia.org/wiki/AppleScript')
Language.create(name: 'Arc', url:'http://en.wikipedia.org/wiki/Arc_(programming_language)')
Language.create(name: 'ARexx', url:'http://en.wikipedia.org/wiki/ARexx')
Language.create(name: 'Argus', url:'http://en.wikipedia.org/wiki/Argus_(programming_language)')
Language.create(name: 'AspectJ', url:'http://en.wikipedia.org/wiki/AspectJ')
Language.create(name: 'Assembly language', url:'http://en.wikipedia.org/wiki/Assembly_language')
Language.create(name: 'ATS', url:'http://en.wikipedia.org/wiki/ATS_(programming_language)')
Language.create(name: 'Ateji PX', url:'http://en.wikipedia.org/wiki/Ateji_PX')
Language.create(name: 'AutoHotkey', url:'http://en.wikipedia.org/wiki/AutoHotkey')
Language.create(name: 'Autocoder', url:'http://en.wikipedia.org/wiki/Autocoder')
Language.create(name: 'AutoIt', url:'http://en.wikipedia.org/wiki/AutoIt')
Language.create(name: 'AutoLISP / Visual LISP', url:'http://en.wikipedia.org/wiki/AutoLISP')
Language.create(name: 'Averest', url:'http://en.wikipedia.org/wiki/Averest')
Language.create(name: 'AWK', url:'http://en.wikipedia.org/wiki/AWK')
Language.create(name: 'Axum', url:'http://en.wikipedia.org/wiki/Axum_(programming_language)')
Language.create(name: 'B', url:'http://en.wikipedia.org/wiki/B_(programming_language)')
Language.create(name: 'Babbage', url:'http://en.wikipedia.org/wiki/Babbage_(programming_language)')
Language.create(name: 'Bash', url:'http://en.wikipedia.org/wiki/Bash_(Unix_shell)')
Language.create(name: 'BASIC', url:'http://en.wikipedia.org/wiki/BASIC')
Language.create(name: 'bc', url:'http://en.wikipedia.org/wiki/Bc_(programming_language)')
Language.create(name: 'BCPL', url:'http://en.wikipedia.org/wiki/BCPL')
Language.create(name: 'BeanShell', url:'http://en.wikipedia.org/wiki/BeanShell')
Language.create(name: 'Batch (Windows/Dos)', url:'http://en.wikipedia.org/wiki/Batch_file')
Language.create(name: 'Bertrand', url:'http://en.wikipedia.org/wiki/Bertrand_(programming_language)')
Language.create(name: 'BETA', url:'http://en.wikipedia.org/wiki/BETA_(programming_language)')
Language.create(name: 'Bigwig', url:'http://en.wikipedia.org/wiki/Bigwig_(programming_language)')
Language.create(name: 'Bistro', url:'http://en.wikipedia.org/wiki/Bistro_(programming_language)')
Language.create(name: 'BitC', url:'http://en.wikipedia.org/wiki/BitC')
Language.create(name: 'BLISS', url:'http://en.wikipedia.org/wiki/BLISS_(programming_language)')
Language.create(name: 'Blue', url:'http://en.wikipedia.org/wiki/Blue_(programming_language)')
Language.create(name: 'Boo', url:'http://en.wikipedia.org/wiki/Boo_(programming_language)')
Language.create(name: 'Boomerang', url:'http://en.wikipedia.org/wiki/Boomerang_(programming_language)')
Language.create(name: 'Bourne shell', url:'http://en.wikipedia.org/wiki/Bourne_shell')
Language.create(name: 'bash', url:'http://en.wikipedia.org/wiki/Bash_(Unix_shell)')
Language.create(name: 'ksh', url:'http://en.wikipedia.org/wiki/Korn_shell')
Language.create(name: 'BREW', url:'http://en.wikipedia.org/wiki/Qualcomm_Brew')
Language.create(name: 'BPEL', url:'http://en.wikipedia.org/wiki/Business_Process_Execution_Language')
Language.create(name: 'C', url:'http://en.wikipedia.org/wiki/C_(programming_language)')
Language.create(name: 'C--', url:'http://en.wikipedia.org/wiki/C--')
Language.create(name: 'C++', url:'http://en.wikipedia.org/wiki/C%2B%2B')
Language.create(name: 'C#', url:'http://en.wikipedia.org/wiki/C_Sharp_(programming_language)')
Language.create(name: 'C/AL', url:'http://en.wikipedia.org/wiki/C/AL')
Language.create(name: 'Caché ObjectScript', url:'http://en.wikipedia.org/wiki/Cach%C3%A9_ObjectScript')
Language.create(name: 'C Shell', url:'http://en.wikipedia.org/wiki/C_Shell')
Language.create(name: 'Caml', url:'http://en.wikipedia.org/wiki/Caml')
Language.create(name: 'Cayenne', url:'http://en.wikipedia.org/wiki/Cayenne_(programming_language)')
Language.create(name: 'CDuce', url:'http://en.wikipedia.org/wiki/CDuce')
Language.create(name: 'Cecil', url:'http://en.wikipedia.org/wiki/Cecil_(programming_language)')
Language.create(name: 'Cel', url:'http://en.wikipedia.org/wiki/Cel_(programming_language)')
Language.create(name: 'Cesil', url:'http://en.wikipedia.org/wiki/Cesil')
Language.create(name: 'Ceylon', url:'http://en.wikipedia.org/wiki/Ceylon_(programming_language)')
Language.create(name: 'CFEngine', url:'http://en.wikipedia.org/wiki/CFEngine')
Language.create(name: 'CFML', url:'http://en.wikipedia.org/wiki/ColdFusion_Markup_Language')
Language.create(name: 'Cg', url:'http://en.wikipedia.org/wiki/Cg_(programming_language)')
Language.create(name: 'Ch', url:'http://en.wikipedia.org/wiki/Ch_(computer_programming)')
Language.create(name: 'Chapel', url:'http://en.wikipedia.org/wiki/Chapel_(programming_language)')
Language.create(name: 'CHAIN', url:'http://en.wikipedia.org/wiki/CHAIN_(programming_language)')
Language.create(name: 'Charity', url:'http://en.wikipedia.org/wiki/Charity_(programming_language)')
Language.create(name: 'Charm', url:'http://en.wikipedia.org/wiki/Charm_(language)')
Language.create(name: 'Chef', url:'http://en.wikipedia.org/wiki/Chef_(programming_language)')
Language.create(name: 'CHILL', url:'http://en.wikipedia.org/wiki/CHILL')
Language.create(name: 'CHIP-8', url:'http://en.wikipedia.org/wiki/CHIP-8')
Language.create(name: 'chomski', url:'http://en.wikipedia.org/wiki/Chomski')
Language.create(name: 'ChucK', url:'http://en.wikipedia.org/wiki/ChucK')
Language.create(name: 'CICS', url:'http://en.wikipedia.org/wiki/CICS')
Language.create(name: 'Cilk', url:'http://en.wikipedia.org/wiki/Cilk')
Language.create(name: 'CL', url:'http://en.wikipedia.org/wiki/AS/400_Control_Language')
Language.create(name: 'Claire', url:'http://en.wikipedia.org/wiki/Claire_(programming_language)')
Language.create(name: 'Clarion', url:'http://en.wikipedia.org/wiki/Clarion_(programming_language)')
Language.create(name: 'Clean', url:'http://en.wikipedia.org/wiki/Clean_(programming_language)')
Language.create(name: 'Clipper', url:'http://en.wikipedia.org/wiki/Clipper_(programming_language)')
Language.create(name: 'CLIST', url:'http://en.wikipedia.org/wiki/CLIST')
Language.create(name: 'Clojure', url:'http://en.wikipedia.org/wiki/Clojure')
Language.create(name: 'CLU', url:'http://en.wikipedia.org/wiki/CLU_(programming_language)')
Language.create(name: 'CMS-2', url:'http://en.wikipedia.org/wiki/CMS-2_(programming_language)')
Language.create(name: 'COBOL', url:'http://en.wikipedia.org/wiki/COBOL')
Language.create(name: 'Cobra', url:'http://en.wikipedia.org/wiki/Cobra_(programming_language)')
Language.create(name: 'CODE', url:'http://en.wikipedia.org/wiki/CODE_(programming_language)')
Language.create(name: 'CoffeeScript', url:'http://en.wikipedia.org/wiki/CoffeeScript')
Language.create(name: 'Cola', url:'http://en.wikipedia.org/wiki/Cola_(programming_language)')
Language.create(name: 'ColdC', url:'http://en.wikipedia.org/wiki/ColdC')
Language.create(name: 'ColdFusion', url:'http://en.wikipedia.org/wiki/ColdFusion')
Language.create(name: 'COMAL', url:'http://en.wikipedia.org/wiki/COMAL')
Language.create(name: 'Combined Programming Language', url:'http://en.wikipedia.org/wiki/Combined_Programming_Language')
Language.create(name: 'COMIT', url:'http://en.wikipedia.org/wiki/COMIT')
Language.create(name: 'Common Intermediate Language', url:'http://en.wikipedia.org/wiki/Common_Intermediate_Language')
Language.create(name: 'Common Lisp', url:'http://en.wikipedia.org/wiki/Common_Lisp')
Language.create(name: 'COMPASS', url:'http://en.wikipedia.org/wiki/COMPASS')
Language.create(name: 'Component Pascal', url:'http://en.wikipedia.org/wiki/Component_Pascal')
Language.create(name: 'Constraint Handling Rules', url:'http://en.wikipedia.org/wiki/Constraint_Handling_Rules')
Language.create(name: 'Converge', url:'http://en.wikipedia.org/wiki/Converge_(programming_language)')
Language.create(name: 'Cool', url:'http://en.wikipedia.org/wiki/Cool_(programming_language)')
Language.create(name: 'Coq', url:'http://en.wikipedia.org/wiki/Coq')
Language.create(name: 'Coral 66', url:'http://en.wikipedia.org/wiki/Coral_66')
Language.create(name: 'Corn', url:'http://en.wikipedia.org/wiki/Corn_(emulator)')
Language.create(name: 'CorVision', url:'http://en.wikipedia.org/wiki/CorVision')
Language.create(name: 'COWSEL', url:'http://en.wikipedia.org/wiki/COWSEL')
Language.create(name: 'CPL', url:'http://en.wikipedia.org/wiki/Combined_Programming_Language')
Language.create(name: 'csh', url:'http://en.wikipedia.org/wiki/C_shell')
Language.create(name: 'CSP', url:'http://en.wikipedia.org/wiki/Communicating_sequential_processes')
Language.create(name: 'Cryptol', url:'http://en.wikipedia.org/wiki/Cryptol')
Language.create(name: 'Csound', url:'http://en.wikipedia.org/wiki/Csound')
Language.create(name: 'CUDA', url:'http://en.wikipedia.org/wiki/CUDA')
Language.create(name: 'Curl', url:'http://en.wikipedia.org/wiki/Curl_(programming_language)')
Language.create(name: 'Curry', url:'http://en.wikipedia.org/wiki/Curry_(programming_language)')
Language.create(name: 'Cyclone', url:'http://en.wikipedia.org/wiki/Cyclone_(programming_language)')
Language.create(name: 'Cython', url:'http://en.wikipedia.org/wiki/Cython')
Language.create(name: 'D', url:'http://en.wikipedia.org/wiki/D_(programming_language)')
Language.create(name: 'DASL', url:'http://en.wikipedia.org/wiki/Datapoint%27s_Advanced_Systems_Language')
Language.create(name: 'DASL', url:'http://en.wikipedia.org/wiki/Distributed_Application_Specification_Language')
Language.create(name: 'Dart', url:'http://en.wikipedia.org/wiki/Dart_(programming_language)')
Language.create(name: 'DataFlex', url:'http://en.wikipedia.org/wiki/DataFlex')
Language.create(name: 'Datalog', url:'http://en.wikipedia.org/wiki/Datalog')
Language.create(name: 'DATATRIEVE', url:'http://en.wikipedia.org/wiki/DATATRIEVE')
Language.create(name: 'dBase', url:'http://en.wikipedia.org/wiki/DBase')
Language.create(name: 'dc', url:'http://en.wikipedia.org/wiki/Dc_(computer_program)')
Language.create(name: 'DCL', url:'http://en.wikipedia.org/wiki/DIGITAL_Command_Language')
Language.create(name: 'Deesel', url:'http://en.wikipedia.org/wiki/Deesel')
Language.create(name: 'Delphi', url:'http://en.wikipedia.org/wiki/Delphi_(programming_language)')
Language.create(name: 'DinkC', url:'http://en.wikipedia.org/wiki/Dink_Smallwood#Modification')
Language.create(name: 'DIBOL', url:'http://en.wikipedia.org/wiki/DIBOL')
Language.create(name: 'Dog', url:'http://en.wikipedia.org/wiki/Sepandar_Kamvar#.22Dog.22_programming_language')
Language.create(name: 'Draco', url:'http://en.wikipedia.org/wiki/Draco_(programming_language)')
Language.create(name: 'DRAKON', url:'http://en.wikipedia.org/wiki/DRAKON')
Language.create(name: 'Dylan', url:'http://en.wikipedia.org/wiki/Dylan_(programming_language)')
Language.create(name: 'DYNAMO', url:'http://en.wikipedia.org/wiki/DYNAMO_(programming_language)')
Language.create(name: 'E', url:'http://en.wikipedia.org/wiki/E_(programming_language)')
Language.create(name: 'E#', url:'http://en.wikipedia.org/wiki/E_Sharp_(programming_language)')
Language.create(name: 'Ease', url:'http://en.wikipedia.org/wiki/Ease_(programming_language)')
Language.create(name: 'Easy PL/I', url:'http://en.wikipedia.org/wiki/PL/I')
Language.create(name: 'Easy Programming Language', url:'http://en.wikipedia.org/wiki/Easy_Programming_Language')
Language.create(name: 'EASYTRIEVE PLUS', url:'http://en.wikipedia.org/wiki/Easytrieve')
Language.create(name: 'ECMAScript', url:'http://en.wikipedia.org/wiki/ECMAScript')
Language.create(name: 'Edinburgh IMP', url:'http://en.wikipedia.org/wiki/Edinburgh_IMP')
Language.create(name: 'EGL', url:'http://en.wikipedia.org/wiki/EGL_(programming_language)')
Language.create(name: 'Eiffel', url:'http://en.wikipedia.org/wiki/Eiffel_(programming_language)')
Language.create(name: 'ELAN', url:'http://en.wikipedia.org/wiki/ELAN_(programming_language)')
Language.create(name: 'Elixir', url:'http://en.wikipedia.org/wiki/Elixir_(programming_language)')
Language.create(name: 'Elm', url:'http://en.wikipedia.org/wiki/Elm_(programming_language)')
Language.create(name: 'Emacs Lisp', url:'http://en.wikipedia.org/wiki/Emacs_Lisp')
Language.create(name: 'Emerald', url:'http://en.wikipedia.org/wiki/Emerald_(programming_language)')
Language.create(name: 'Epigram', url:'http://en.wikipedia.org/wiki/Epigram_(programming_language)')
Language.create(name: 'EPL', url:'http://en.wikipedia.org/wiki/Easy_Programming_Language')
Language.create(name: 'Erlang', url:'http://en.wikipedia.org/wiki/Erlang_(programming_language)')
Language.create(name: 'es', url:'http://en.wikipedia.org/wiki/Es_(Unix_shell)')
Language.create(name: 'Escher', url:'http://en.wikipedia.org/wiki/Escher_(programming_language)')
Language.create(name: 'ESPOL', url:'http://en.wikipedia.org/wiki/Executive_Systems_Problem_Oriented_Language')
Language.create(name: 'Esterel', url:'http://en.wikipedia.org/wiki/Esterel')
Language.create(name: 'Etoys', url:'http://en.wikipedia.org/wiki/Etoys_(programming_language)')
Language.create(name: 'Euclid', url:'http://en.wikipedia.org/wiki/Euclid_(programming_language)')
Language.create(name: 'Euler', url:'http://en.wikipedia.org/wiki/Euler_(programming_language)')
Language.create(name: 'Euphoria', url:'http://en.wikipedia.org/wiki/Euphoria_(programming_language)')
Language.create(name: 'EusLisp Robot Programming Language', url:'http://en.wikipedia.org/wiki/EusLisp_Robot_Programming_Language')
Language.create(name: 'CMS EXEC', url:'http://en.wikipedia.org/wiki/CMS_EXEC')
Language.create(name: 'EXEC 2', url:'http://en.wikipedia.org/wiki/EXEC_2')
Language.create(name: 'Executable UML', url:'http://en.wikipedia.org/wiki/Executable_UML')
Language.create(name: 'F', url:'http://en.wikipedia.org/wiki/F_(programming_language)')
Language.create(name: 'F#', url:'http://en.wikipedia.org/wiki/F_Sharp_(programming_language)')
Language.create(name: 'Factor', url:'http://en.wikipedia.org/wiki/Factor_(programming_language)')
Language.create(name: 'Falcon', url:'http://en.wikipedia.org/wiki/Falcon_(programming_language)')
Language.create(name: 'Fantom', url:'http://en.wikipedia.org/wiki/Fantom_(programming_language)')
Language.create(name: 'FAUST', url:'http://en.wikipedia.org/wiki/FAUST_(programming_language)')
Language.create(name: 'FFP', url:'http://en.wikipedia.org/wiki/FFP_(programming_language)')
Language.create(name: 'Fjölnir', url:'http://en.wikipedia.org/wiki/Fj%C3%B6lnir_(programming_language)')
Language.create(name: 'FL', url:'http://en.wikipedia.org/wiki/FL_(programming_language)')
Language.create(name: 'Flavors', url:'http://en.wikipedia.org/wiki/Flavors_(programming_language)')
Language.create(name: 'Flex', url:'http://en.wikipedia.org/wiki/Flex_(language)')
Language.create(name: 'FLOW-MATIC', url:'http://en.wikipedia.org/wiki/FLOW-MATIC')
Language.create(name: 'FOCAL', url:'http://en.wikipedia.org/wiki/FOCAL_(programming_language)')
Language.create(name: 'FOCUS', url:'http://en.wikipedia.org/wiki/FOCUS')
Language.create(name: 'FOIL', url:'http://en.wikipedia.org/wiki/FOIL_(programming_language)')
Language.create(name: 'FORMAC', url:'http://en.wikipedia.org/wiki/FORMAC_(programming_language)')
Language.create(name: '@Formula', url:'http://en.wikipedia.org/wiki/Formula_language')
Language.create(name: 'Forth', url:'http://en.wikipedia.org/wiki/Forth_(programming_language)')
Language.create(name: 'Fortran', url:'http://en.wikipedia.org/wiki/Fortran')
Language.create(name: 'Fortress', url:'http://en.wikipedia.org/wiki/Fortress_(programming_language)')
Language.create(name: 'FoxBase', url:'http://en.wikipedia.org/wiki/FoxBase')
Language.create(name: 'FoxPro', url:'http://en.wikipedia.org/wiki/FoxPro_(disambiguation)')
Language.create(name: 'FP', url:'http://en.wikipedia.org/wiki/FP_(programming_language)')
Language.create(name: 'FPr', url:'http://en.wikipedia.org/wiki/FPr_(programming_language)')
Language.create(name: 'Franz Lisp', url:'http://en.wikipedia.org/wiki/Franz_Lisp')
Language.create(name: 'Frege', url:'http://en.wikipedia.org/wiki/Frege_(programming_language)')
Language.create(name: 'F-Script', url:'http://en.wikipedia.org/wiki/F-Script_(programming_language)')
Language.create(name: 'G', url:'http://en.wikipedia.org/wiki/G_(programming_language)')
Language.create(name: 'Google Apps Script', url:'http://en.wikipedia.org/wiki/Google_Apps_Script')
Language.create(name: 'Game Maker Language', url:'http://en.wikipedia.org/wiki/GameMaker:_Studio')
Language.create(name: 'GameMonkey Script', url:'http://en.wikipedia.org/wiki/GameMonkey_Script')
Language.create(name: 'GAMS', url:'http://en.wikipedia.org/wiki/General_Algebraic_Modeling_System')
Language.create(name: 'GAP', url:'http://en.wikipedia.org/wiki/GAP_computer_algebra_system')
Language.create(name: 'G-code', url:'http://en.wikipedia.org/wiki/G-code')
Language.create(name: 'Genie', url:'http://en.wikipedia.org/wiki/Genie_(programming_language)')
Language.create(name: 'GDL', url:'http://en.wikipedia.org/wiki/Geometric_Description_Language')
Language.create(name: 'GJ', url:'http://en.wikipedia.org/wiki/Generic_Java')
Language.create(name: 'GEORGE', url:'http://en.wikipedia.org/wiki/GEORGE_(programming_language)')
Language.create(name: 'GLSL', url:'http://en.wikipedia.org/wiki/GLSL')
Language.create(name: 'GNU E', url:'http://en.wikipedia.org/wiki/GNU_E')
Language.create(name: 'GM', url:'http://en.wikipedia.org/wiki/Golden_master')
Language.create(name: 'Go', url:'http://en.wikipedia.org/wiki/Go_(programming_language)')
Language.create(name: 'Go!', url:'http://en.wikipedia.org/wiki/Go!_(programming_language)')
Language.create(name: 'GOAL', url:'http://en.wikipedia.org/wiki/Game_Oriented_Assembly_Lisp')
Language.create(name: 'Gödel', url:'http://en.wikipedia.org/wiki/G%C3%B6del_(programming_language)')
Language.create(name: 'Godiva', url:'http://en.wikipedia.org/wiki/Godiva_(programming_language)')
Language.create(name: 'GOM (Good Old Mad)', url:'http://en.wikipedia.org/wiki/MAD_(programming_language)')
Language.create(name: 'Goo', url:'http://en.wikipedia.org/wiki/Goo_(programming_language)')
Language.create(name: 'Gosu', url:'http://en.wikipedia.org/wiki/Gosu_(programming_language)')
Language.create(name: 'GOTRAN', url:'http://en.wikipedia.org/wiki/IBM_1620#GOTRAN')
Language.create(name: 'GPSS', url:'http://en.wikipedia.org/wiki/GPSS')
Language.create(name: 'GraphTalk', url:'http://en.wikipedia.org/wiki/Computer_Sciences_Corporation')
Language.create(name: 'GRASS', url:'http://en.wikipedia.org/wiki/GRASS_(programming_language)')
Language.create(name: 'Groovy', url:'http://en.wikipedia.org/wiki/Groovy_(programming_language)')
Language.create(name: 'Hack', url:'http://en.wikipedia.org/wiki/Hack_(programming_language)')
Language.create(name: 'HAL/S', url:'http://en.wikipedia.org/wiki/HAL/S')
Language.create(name: 'Hamilton C shell', url:'http://en.wikipedia.org/wiki/Hamilton_C_shell')
Language.create(name: 'Harbour', url:'http://en.wikipedia.org/wiki/Harbour_(software)')
Language.create(name: 'Hartmann pipelines', url:'http://en.wikipedia.org/wiki/Hartmann_pipeline')
Language.create(name: 'Haskell', url:'http://en.wikipedia.org/wiki/Haskell_(programming_language)')
Language.create(name: 'Haxe', url:'http://en.wikipedia.org/wiki/Haxe')
Language.create(name: 'High Level Assembly', url:'http://en.wikipedia.org/wiki/High_Level_Assembly')
Language.create(name: 'HLSL', url:'http://en.wikipedia.org/wiki/High_Level_Shader_Language')
Language.create(name: 'Hop', url:'http://en.wikipedia.org/wiki/Hop_(software)')
Language.create(name: 'Hope', url:'http://en.wikipedia.org/wiki/Hope_(programming_language)')
Language.create(name: 'Hugo', url:'http://en.wikipedia.org/wiki/Hugo_(programming_language)')
Language.create(name: 'Hume', url:'http://en.wikipedia.org/wiki/Hume_(language)')
Language.create(name: 'HyperTalk', url:'http://en.wikipedia.org/wiki/HyperTalk')
Language.create(name: 'IBM Basic assembly language', url:'http://en.wikipedia.org/wiki/IBM_Basic_assembly_language')
Language.create(name: 'IBM HAScript', url:'http://en.wikipedia.org/wiki/IBM_HAScript')
Language.create(name: 'IBM Informix-4GL', url:'http://en.wikipedia.org/wiki/IBM_Informix-4GL')
Language.create(name: 'IBM RPG', url:'http://en.wikipedia.org/wiki/IBM_RPG')
Language.create(name: 'ICI', url:'http://en.wikipedia.org/wiki/ICI_(programming_language)')
Language.create(name: 'Icon', url:'http://en.wikipedia.org/wiki/Icon_(programming_language)')
Language.create(name: 'Id', url:'http://en.wikipedia.org/wiki/Id_(programming_language)')
Language.create(name: 'IDL', url:'http://en.wikipedia.org/wiki/IDL_(programming_language)')
Language.create(name: 'Idris', url:'http://en.wikipedia.org/wiki/Idris_(programming_language)')
Language.create(name: 'IMP', url:'http://en.wikipedia.org/wiki/IMP_(programming_language)')
Language.create(name: 'Inform', url:'http://en.wikipedia.org/wiki/Inform')
Language.create(name: 'Io', url:'http://en.wikipedia.org/wiki/Io_(programming_language)')
Language.create(name: 'Ioke', url:'http://en.wikipedia.org/wiki/Ioke_(programming_language)')
Language.create(name: 'IPL', url:'http://en.wikipedia.org/wiki/Information_Processing_Language')
Language.create(name: 'IPTSCRAE', url:'http://en.wikipedia.org/wiki/IPTSCRAE')
Language.create(name: 'ISLISP', url:'http://en.wikipedia.org/wiki/ISLISP')
Language.create(name: 'ISPF', url:'http://en.wikipedia.org/wiki/ISPF')
Language.create(name: 'ISWIM', url:'http://en.wikipedia.org/wiki/ISWIM')
Language.create(name: 'J', url:'http://en.wikipedia.org/wiki/J_(programming_language)')
Language.create(name: 'J#', url:'http://en.wikipedia.org/wiki/J_Sharp')
Language.create(name: 'J++', url:'http://en.wikipedia.org/wiki/Visual_J%2B%2B')
Language.create(name: 'JADE', url:'http://en.wikipedia.org/wiki/JADE_(programming_language)')
Language.create(name: 'Jako', url:'http://en.wikipedia.org/wiki/Jako_(programming_language)')
Language.create(name: 'JAL', url:'http://en.wikipedia.org/wiki/JAL_(compiler)')
Language.create(name: 'Janus', url:'http://en.wikipedia.org/wiki/Janus_(programming_language)')
Language.create(name: 'JASS', url:'http://en.wikipedia.org/wiki/JASS')
Language.create(name: 'Java', url:'http://en.wikipedia.org/wiki/Java_(programming_language)')
Language.create(name: 'JavaScript', url:'http://en.wikipedia.org/wiki/JavaScript')
Language.create(name: 'JCL', url:'http://en.wikipedia.org/wiki/Job_Control_Language')
Language.create(name: 'JEAN', url:'http://en.wikipedia.org/wiki/JEAN')
Language.create(name: 'Join Java', url:'http://en.wikipedia.org/wiki/Join_Java')
Language.create(name: 'JOSS', url:'http://en.wikipedia.org/wiki/JOSS')
Language.create(name: 'Joule', url:'http://en.wikipedia.org/wiki/Joule_(programming_language)')
Language.create(name: 'JOVIAL', url:'http://en.wikipedia.org/wiki/JOVIAL')
Language.create(name: 'Joy', url:'http://en.wikipedia.org/wiki/Joy_(programming_language)')
Language.create(name: 'JScript', url:'http://en.wikipedia.org/wiki/JScript')
Language.create(name: 'JScript .NET', url:'http://en.wikipedia.org/wiki/JScript_.NET')
Language.create(name: 'JavaFX Script', url:'http://en.wikipedia.org/wiki/JavaFX_Script')
Language.create(name: 'Julia', url:'http://en.wikipedia.org/wiki/Julia_(programming_language)')
Language.create(name: 'Jython', url:'http://en.wikipedia.org/wiki/Jython')
Language.create(name: 'K', url:'http://en.wikipedia.org/wiki/K_(programming_language)')
Language.create(name: 'Kaleidoscope', url:'http://en.wikipedia.org/wiki/Kaleidoscope_(programming_language)')
Language.create(name: 'Karel', url:'http://en.wikipedia.org/wiki/Karel_(programming_language)')
Language.create(name: 'Karel++', url:'http://en.wikipedia.org/wiki/Karel%2B%2B')
Language.create(name: 'KEE', url:'http://en.wikipedia.org/wiki/IntelliCorp_(Software)')
Language.create(name: 'Kixtart', url:'http://en.wikipedia.org/wiki/KiXtart')
Language.create(name: 'Klerer-May System', url:'http://en.wikipedia.org/wiki/Klerer-May_System')
Language.create(name: 'KIF', url:'http://en.wikipedia.org/wiki/Knowledge_Interchange_Format')
Language.create(name: 'Kojo', url:'http://en.wikipedia.org/wiki/Kojo_(programming_language)')
Language.create(name: 'Kotlin', url:'http://en.wikipedia.org/wiki/Kotlin_(programming_language)')
Language.create(name: 'KRC', url:'http://en.wikipedia.org/wiki/Kent_Recursive_Calculator')
Language.create(name: 'KRL', url:'http://en.wikipedia.org/wiki/KRL_(programming_language)')
Language.create(name: 'KUKA', url:'http://en.wikipedia.org/wiki/KUKA')
Language.create(name: 'KRYPTON', url:'http://en.wikipedia.org/wiki/KRYPTON')
Language.create(name: 'ksh', url:'http://en.wikipedia.org/wiki/Korn_shell')
Language.create(name: 'L', url:'http://en.wikipedia.org/wiki/L_(programming_language)')
Language.create(name: 'L# .NET', url:'http://en.wikipedia.org/wiki/L_Sharp')
Language.create(name: 'LabVIEW', url:'http://en.wikipedia.org/wiki/LabVIEW')
Language.create(name: 'Ladder', url:'http://en.wikipedia.org/wiki/Ladder_logic')
Language.create(name: 'Lagoona', url:'http://en.wikipedia.org/wiki/Lagoona_(programming_language)')
Language.create(name: 'LANSA', url:'http://en.wikipedia.org/wiki/LANSA_(development_environment)')
Language.create(name: 'Lasso', url:'http://en.wikipedia.org/wiki/Lasso_(programming_language)')
Language.create(name: 'LaTeX', url:'http://en.wikipedia.org/wiki/LaTeX')
Language.create(name: 'Lava', url:'http://en.wikipedia.org/wiki/Lava_(programming_language)')
Language.create(name: 'LC-3', url:'http://en.wikipedia.org/wiki/LC-3')
Language.create(name: 'Leda', url:'http://en.wikipedia.org/wiki/Leda_(programming_language)')
Language.create(name: 'Legoscript', url:'http://en.wikipedia.org/wiki/Lego_Mindstorms')
Language.create(name: 'LIL', url:'http://en.wikipedia.org/wiki/Little_Implementation_Language')
Language.create(name: 'LilyPond', url:'http://en.wikipedia.org/wiki/LilyPond')
Language.create(name: 'Limbo', url:'http://en.wikipedia.org/wiki/Limbo_(programming_language)')
Language.create(name: 'Limnor', url:'http://en.wikipedia.org/wiki/Limnor')
Language.create(name: 'LINC', url:'http://en.wikipedia.org/wiki/LINC_4GL')
Language.create(name: 'Lingo', url:'http://en.wikipedia.org/wiki/Lingo_(programming_language)')
Language.create(name: 'Linoleum', url:'http://en.wikipedia.org/wiki/Linoleum_(programming_language)')
Language.create(name: 'LIS', url:'http://en.wikipedia.org/wiki/LIS_(programming_language)')
Language.create(name: 'LISA', url:'http://en.wikipedia.org/wiki/Language_for_Instruction_Set_Architecture')
Language.create(name: 'Lisaac', url:'http://en.wikipedia.org/wiki/Lisaac')
Language.create(name: 'Lisp', url:'http://en.wikipedia.org/wiki/Lisp_(programming_language)')
Language.create(name: 'Lite-C', url:'http://en.wikipedia.org/wiki/Lite-C')
Language.create(name: 'Lithe', url:'http://en.wikipedia.org/wiki/Lithe_(programming_language)')
Language.create(name: 'Little b', url:'http://en.wikipedia.org/wiki/Little_b_(programming_language)')
Language.create(name: 'Logo', url:'http://en.wikipedia.org/wiki/Logo_(programming_language)')
Language.create(name: 'Logtalk', url:'http://en.wikipedia.org/wiki/Logtalk')
Language.create(name: 'LotusScript', url:'http://en.wikipedia.org/wiki/LotusScript')
Language.create(name: 'LPC', url:'http://en.wikipedia.org/wiki/LPC_(programming_language)')
Language.create(name: 'LSE', url:'http://en.wikipedia.org/wiki/LSE_(programming_language)')
Language.create(name: 'LSL', url:'http://en.wikipedia.org/wiki/Linden_Scripting_Language')
Language.create(name: 'LiveCode', url:'http://en.wikipedia.org/wiki/LiveCode')
Language.create(name: 'LiveScript', url:'http://en.wikipedia.org/wiki/LiveScript')
Language.create(name: 'Lua', url:'http://en.wikipedia.org/wiki/Lua_(programming_language)')
Language.create(name: 'Lucid', url:'http://en.wikipedia.org/wiki/Lucid_(programming_language)')
Language.create(name: 'Lustre', url:'http://en.wikipedia.org/wiki/Lustre_(programming_language)')
Language.create(name: 'LYaPAS', url:'http://en.wikipedia.org/wiki/LYaPAS')
Language.create(name: 'Lynx', url:'http://en.wikipedia.org/wiki/Lynx_(programming_language)')
Language.create(name: 'M2001', url:'http://en.wikipedia.org/wiki/M2001')
Language.create(name: 'M4', url:'http://en.wikipedia.org/wiki/M4_(computer_language)')
Language.create(name: 'M#', url:'http://en.wikipedia.org/wiki/M_Sharp_(programming_language)')
Language.create(name: 'Machine code', url:'http://en.wikipedia.org/wiki/Machine_code')
Language.create(name: 'MAD', url:'http://en.wikipedia.org/wiki/MAD_(programming_language)')
Language.create(name: 'MAD/I', url:'http://en.wikipedia.org/wiki/MAD_(programming_language)')
Language.create(name: 'Magik', url:'http://en.wikipedia.org/wiki/Magik_(programming_language)')
Language.create(name: 'Magma', url:'http://en.wikipedia.org/wiki/Magma_computer_algebra_system')
Language.create(name: 'make', url:'http://en.wikipedia.org/wiki/Make_(software)')
Language.create(name: 'Maple', url:'http://en.wikipedia.org/wiki/Maple_(software)')
Language.create(name: 'MAPPER', url:'http://en.wikipedia.org/wiki/MAPPER')
Language.create(name: 'MARK-IV', url:'http://en.wikipedia.org/wiki/MARK_IV_(software)')
Language.create(name: 'Mary', url:'http://en.wikipedia.org/wiki/Mary_(programming_language)')
Language.create(name: 'MASM Microsoft Assembly x86', url:'http://en.wikipedia.org/wiki/Microsoft_Macro_Assembler')
Language.create(name: 'Mathematica', url:'http://en.wikipedia.org/wiki/Mathematica')
Language.create(name: 'MATLAB', url:'http://en.wikipedia.org/wiki/MATLAB')
Language.create(name: 'Maxima', url:'http://en.wikipedia.org/wiki/Maxima_(software)')
Language.create(name: 'Macsyma', url:'http://en.wikipedia.org/wiki/Macsyma')
Language.create(name: 'Max', url:'http://en.wikipedia.org/wiki/Max_(software)')
Language.create(name: 'MaxScript', url:'http://en.wikipedia.org/wiki/Autodesk_3ds_Max')
Language.create(name: 'Maya (MEL)', url:'http://en.wikipedia.org/wiki/Maya_Embedded_Language')
Language.create(name: 'MDL', url:'http://en.wikipedia.org/wiki/MDL_(programming_language)')
Language.create(name: 'Mercury', url:'http://en.wikipedia.org/wiki/Mercury_(programming_language)')
Language.create(name: 'Mesa', url:'http://en.wikipedia.org/wiki/Mesa_(programming_language)')
Language.create(name: 'Metacard', url:'http://en.wikipedia.org/wiki/Metacard')
Language.create(name: 'Metafont', url:'http://en.wikipedia.org/wiki/Metafont')
Language.create(name: 'Microcode', url:'http://en.wikipedia.org/wiki/Microassembler')
Language.create(name: 'MicroScript', url:'http://en.wikipedia.org/wiki/MicroScript_(programming_language)')
Language.create(name: 'MIIS', url:'http://en.wikipedia.org/wiki/MIIS_(programming_language)')
Language.create(name: 'MillScript', url:'http://en.wikipedia.org/wiki/MillScript')
Language.create(name: 'MIMIC', url:'http://en.wikipedia.org/wiki/MIMIC')
Language.create(name: 'Mirah', url:'http://en.wikipedia.org/wiki/Mirah_(programming_language)')
Language.create(name: 'Miranda', url:'http://en.wikipedia.org/wiki/Miranda_(programming_language)')
Language.create(name: 'MIVA Script', url:'http://en.wikipedia.org/wiki/MIVA_Script')
Language.create(name: 'ML', url:'http://en.wikipedia.org/wiki/ML_(programming_language)')
Language.create(name: 'Moby', url:'http://en.wikipedia.org/wiki/Moby_(programming_language)')
Language.create(name: 'Model 204', url:'http://en.wikipedia.org/wiki/Model_204')
Language.create(name: 'Modelica', url:'http://en.wikipedia.org/wiki/Modelica')
Language.create(name: 'Modula', url:'http://en.wikipedia.org/wiki/Modula')
Language.create(name: 'Modula-2', url:'http://en.wikipedia.org/wiki/Modula-2')
Language.create(name: 'Modula-3', url:'http://en.wikipedia.org/wiki/Modula-3')
Language.create(name: 'Mohol', url:'http://en.wikipedia.org/wiki/Mohol_programming_languages')
Language.create(name: 'MOO', url:'http://en.wikipedia.org/wiki/MOO_(programming_language)')
Language.create(name: 'Mortran', url:'http://en.wikipedia.org/wiki/Mortran')
Language.create(name: 'Mouse', url:'http://en.wikipedia.org/wiki/Mouse_(programming_language)')
Language.create(name: 'MPD', url:'http://en.wikipedia.org/wiki/MPD_(programming_language)')
Language.create(name: 'CIL', url:'http://en.wikipedia.org/wiki/Common_Intermediate_Language')
Language.create(name: 'MSL', url:'http://en.wikipedia.org/wiki/MIRC_scripting_language')
Language.create(name: 'MUMPS', url:'http://en.wikipedia.org/wiki/MUMPS')
Language.create(name: 'Mystic Programming Language', url:'http://en.wikipedia.org/wiki/Mystic_BBS')
Language.create(name: 'NASM', url:'http://en.wikipedia.org/wiki/Netwide_Assembler')
Language.create(name: 'NATURAL', url:'http://en.wikipedia.org/wiki/NATURAL')
Language.create(name: 'Napier88', url:'http://en.wikipedia.org/wiki/Napier88')
Language.create(name: 'Neko', url:'http://en.wikipedia.org/wiki/Neko_(programming_language)')
Language.create(name: 'Nemerle', url:'http://en.wikipedia.org/wiki/Nemerle')
Language.create(name: 'nesC', url:'http://en.wikipedia.org/wiki/NesC')
Language.create(name: 'NESL', url:'http://en.wikipedia.org/wiki/NESL')
Language.create(name: 'Net.Data', url:'http://en.wikipedia.org/wiki/Net.Data')
Language.create(name: 'NetLogo', url:'http://en.wikipedia.org/wiki/NetLogo')
Language.create(name: 'NetRexx', url:'http://en.wikipedia.org/wiki/NetRexx')
Language.create(name: 'NewLISP', url:'http://en.wikipedia.org/wiki/NewLISP')
Language.create(name: 'NEWP', url:'http://en.wikipedia.org/wiki/NEWP')
Language.create(name: 'Newspeak', url:'http://en.wikipedia.org/wiki/Newspeak_(programming_language)')
Language.create(name: 'NewtonScript', url:'http://en.wikipedia.org/wiki/NewtonScript')
Language.create(name: 'NGL', url:'http://en.wikipedia.org/wiki/NGL_(programming_language)')
Language.create(name: 'Nial', url:'http://en.wikipedia.org/wiki/Nial')
Language.create(name: 'Nice', url:'http://en.wikipedia.org/wiki/Nice_(programming_language)')
Language.create(name: 'Nickle', url:'http://en.wikipedia.org/wiki/Nickle_(programming_language)')
Language.create(name: 'Nim', url:'http://en.wikipedia.org/wiki/Nim_(programming_language)')
Language.create(name: 'NPL', url:'http://en.wikipedia.org/wiki/NORD_Programming_Language')
Language.create(name: 'Not eXactly C', url:'http://en.wikipedia.org/wiki/Not_eXactly_C')
Language.create(name: 'Not Quite C', url:'http://en.wikipedia.org/wiki/Not_Quite_C')
Language.create(name: 'NSIS', url:'http://en.wikipedia.org/wiki/Nullsoft_Scriptable_Install_System')
Language.create(name: 'Nu', url:'http://en.wikipedia.org/wiki/Nu_(programming_language)')
Language.create(name: 'NWScript', url:'http://en.wikipedia.org/wiki/NWScript')
Language.create(name: 'NXT-G', url:'http://en.wikipedia.org/wiki/NXT-G')
Language.create(name: 'o:XML', url:'http://en.wikipedia.org/wiki/O:XML')
Language.create(name: 'Oak', url:'http://en.wikipedia.org/wiki/Oak_(programming_language)')
Language.create(name: 'Oberon', url:'http://en.wikipedia.org/wiki/Oberon_(programming_language)')
Language.create(name: 'OBJ2', url:'http://en.wikipedia.org/wiki/OBJ2')
Language.create(name: 'Object Lisp', url:'http://en.wikipedia.org/wiki/Object_Lisp')
Language.create(name: 'ObjectLOGO', url:'http://en.wikipedia.org/wiki/ObjectLOGO')
Language.create(name: 'Object REXX', url:'http://en.wikipedia.org/wiki/Object_REXX')
Language.create(name: 'Object Pascal', url:'http://en.wikipedia.org/wiki/Object_Pascal')
Language.create(name: 'Objective-C', url:'http://en.wikipedia.org/wiki/Objective-C')
Language.create(name: 'Objective-J', url:'http://en.wikipedia.org/wiki/Objective-J')
Language.create(name: 'Obliq', url:'http://en.wikipedia.org/wiki/Obliq')
Language.create(name: 'OCaml', url:'http://en.wikipedia.org/wiki/OCaml')
Language.create(name: 'occam', url:'http://en.wikipedia.org/wiki/Occam_(programming_language)')
Language.create(name: 'occam-π', url:'http://en.wikipedia.org/wiki/Occam-%CF%80')
Language.create(name: 'Octave', url:'http://en.wikipedia.org/wiki/GNU_Octave')
Language.create(name: 'OmniMark', url:'http://en.wikipedia.org/wiki/OmniMark')
Language.create(name: 'Onyx', url:'http://en.wikipedia.org/wiki/Onyx_(programming_language)')
Language.create(name: 'Opa', url:'http://en.wikipedia.org/wiki/Opa_(programming_language)')
Language.create(name: 'Opal', url:'http://en.wikipedia.org/wiki/Opal_(programming_language)')
Language.create(name: 'OpenCL', url:'http://en.wikipedia.org/wiki/OpenCL')
Language.create(name: 'OpenEdge ABL', url:'http://en.wikipedia.org/wiki/OpenEdge_Advanced_Business_Language')
Language.create(name: 'OPL', url:'http://en.wikipedia.org/wiki/Open_Programming_Language')
Language.create(name: 'OPS5', url:'http://en.wikipedia.org/wiki/OPS5')
Language.create(name: 'OptimJ', url:'http://en.wikipedia.org/wiki/OptimJ')
Language.create(name: 'Orc', url:'http://en.wikipedia.org/wiki/Orc_(programming_language)')
Language.create(name: 'ORCA/Modula-2', url:'http://en.wikipedia.org/wiki/ORCA/Modula-2')
Language.create(name: 'Oriel', url:'http://en.wikipedia.org/wiki/Oriel_(scripting_language)')
Language.create(name: 'Orwell', url:'http://en.wikipedia.org/wiki/Orwell_(programming_language)')
Language.create(name: 'Oxygene', url:'http://en.wikipedia.org/wiki/Oxygene_(programming_language)')
Language.create(name: 'Oz', url:'http://en.wikipedia.org/wiki/Oz_(programming_language)')
Language.create(name: 'P′′', url:'http://en.wikipedia.org/wiki/P%E2%80%B2%E2%80%B2')
Language.create(name: 'P#', url:'http://en.wikipedia.org/wiki/P_Sharp')
Language.create(name: 'ParaSail (programming language)', url:'http://en.wikipedia.org/wiki/ParaSail_(programming_language)')
Language.create(name: 'PARI/GP', url:'http://en.wikipedia.org/wiki/PARI/GP')
Language.create(name: 'Pascal', url:'http://en.wikipedia.org/wiki/Pascal_(programming_language)')
Language.create(name: 'PCASTL', url:'http://en.wikipedia.org/wiki/PCASTL')
Language.create(name: 'PCF', url:'http://en.wikipedia.org/wiki/Programming_language_for_Computable_Functions')
Language.create(name: 'PEARL', url:'http://en.wikipedia.org/wiki/PEARL_(programming_language)')
Language.create(name: 'PeopleCode', url:'http://en.wikipedia.org/wiki/PeopleCode')
Language.create(name: 'Perl', url:'http://en.wikipedia.org/wiki/Perl')
Language.create(name: 'PDL', url:'http://en.wikipedia.org/wiki/Perl_Data_Language')
Language.create(name: 'Perl6', url:'http://en.wikipedia.org/wiki/Perl6')
Language.create(name: 'PHP', url:'http://en.wikipedia.org/wiki/PHP')
Language.create(name: 'Phrogram', url:'http://en.wikipedia.org/wiki/Phrogram')
Language.create(name: 'Pico', url:'http://en.wikipedia.org/wiki/Pico_(programming_language)')
Language.create(name: 'Picolisp', url:'http://en.wikipedia.org/wiki/Picolisp')
Language.create(name: 'Pict', url:'http://en.wikipedia.org/wiki/Pict_(programming_language)')
Language.create(name: 'Pike', url:'http://en.wikipedia.org/wiki/Pike_(programming_language)')
Language.create(name: 'PIKT', url:'http://en.wikipedia.org/wiki/PIKT')
Language.create(name: 'PILOT', url:'http://en.wikipedia.org/wiki/PILOT')
Language.create(name: 'Pipelines', url:'http://en.wikipedia.org/wiki/Hartmann_pipeline')
Language.create(name: 'Pizza', url:'http://en.wikipedia.org/wiki/Pizza_(programming_language)')
Language.create(name: 'PL-11', url:'http://en.wikipedia.org/wiki/PL-11')
Language.create(name: 'PL/0', url:'http://en.wikipedia.org/wiki/PL/0')
Language.create(name: 'PL/B', url:'http://en.wikipedia.org/wiki/Programming_Language_for_Business')
Language.create(name: 'PL/C', url:'http://en.wikipedia.org/wiki/PL/C')
Language.create(name: 'PL/I', url:'http://en.wikipedia.org/wiki/PL/I')
Language.create(name: 'PL/M', url:'http://en.wikipedia.org/wiki/PL/M')
Language.create(name: 'PL/P', url:'http://en.wikipedia.org/wiki/PL/P')
Language.create(name: 'PL/SQL', url:'http://en.wikipedia.org/wiki/PL/SQL')
Language.create(name: 'PL360', url:'http://en.wikipedia.org/wiki/PL360')
Language.create(name: 'PLANC', url:'http://en.wikipedia.org/wiki/PLANC')
Language.create(name: 'Plankalkül', url:'http://en.wikipedia.org/wiki/Plankalk%C3%BCl')
Language.create(name: 'Planner', url:'http://en.wikipedia.org/wiki/Planner_(programming_language)')
Language.create(name: 'PLEX', url:'http://en.wikipedia.org/wiki/PLEX_(programming_language)')
Language.create(name: 'PLEXIL', url:'http://en.wikipedia.org/wiki/PLEXIL')
Language.create(name: 'Plus', url:'http://en.wikipedia.org/wiki/Plus_(programming_language)')
Language.create(name: 'POP-11', url:'http://en.wikipedia.org/wiki/POP-11')
Language.create(name: 'PostScript', url:'http://en.wikipedia.org/wiki/PostScript')
Language.create(name: 'PortablE', url:'http://en.wikipedia.org/wiki/Amiga_E#PortablE')
Language.create(name: 'Powerhouse', url:'http://en.wikipedia.org/wiki/Powerhouse_(programming_language)')
Language.create(name: 'PowerBuilder', url:'http://en.wikipedia.org/wiki/PowerBuilder')
Language.create(name: 'PowerShell', url:'http://en.wikipedia.org/wiki/PowerShell')
Language.create(name: 'PPL', url:'http://en.wikipedia.org/wiki/Polymorphic_Programming_Language')
Language.create(name: 'Processing', url:'http://en.wikipedia.org/wiki/Processing_(programming_language)')
Language.create(name: 'Processing.js', url:'http://en.wikipedia.org/wiki/Processing.js')
Language.create(name: 'Prograph', url:'http://en.wikipedia.org/wiki/Prograph')
Language.create(name: 'PROIV', url:'http://en.wikipedia.org/wiki/PROIV')
Language.create(name: 'Prolog', url:'http://en.wikipedia.org/wiki/Prolog')
Language.create(name: 'PROMAL', url:'http://en.wikipedia.org/wiki/PROMAL')
Language.create(name: 'Promela', url:'http://en.wikipedia.org/wiki/Promela')
Language.create(name: 'PROSE modeling language', url:'http://en.wikipedia.org/wiki/PROSE_modeling_language')
Language.create(name: 'PROTEL', url:'http://en.wikipedia.org/wiki/Protel')
Language.create(name: 'ProvideX', url:'http://en.wikipedia.org/wiki/ProvideX')
Language.create(name: 'Pro*C', url:'http://en.wikipedia.org/wiki/Pro*C')
Language.create(name: 'Pure', url:'http://en.wikipedia.org/wiki/Pure_(programming_language)')
Language.create(name: 'Python', url:'http://en.wikipedia.org/wiki/Python_(programming_language)')
Language.create(name: 'Q (equational programming language)', url:'http://en.wikipedia.org/wiki/Q_(equational_programming_language)')
Language.create(name: 'Q (programming language from Kx Systems)', url:'http://en.wikipedia.org/wiki/Q_(programming_language_from_Kx_Systems)')
Language.create(name: 'Qalb', url:'http://en.wikipedia.org/wiki/Qalb_(programming_language)')
Language.create(name: 'QtScript', url:'http://en.wikipedia.org/wiki/QtScript')
Language.create(name: 'QuakeC', url:'http://en.wikipedia.org/wiki/QuakeC')
Language.create(name: 'QPL', url:'http://en.wikipedia.org/wiki/Quantum_programming')
Language.create(name: 'R', url:'http://en.wikipedia.org/wiki/R_(programming_language)')
Language.create(name: 'R++', url:'http://en.wikipedia.org/wiki/R%2B%2B')
Language.create(name: 'Racket', url:'http://en.wikipedia.org/wiki/Racket_(programming_language)')
Language.create(name: 'RAPID', url:'http://en.wikipedia.org/wiki/RAPID')
Language.create(name: 'Rapira', url:'http://en.wikipedia.org/wiki/Rapira')
Language.create(name: 'Ratfiv', url:'http://en.wikipedia.org/wiki/Ratfiv')
Language.create(name: 'Ratfor', url:'http://en.wikipedia.org/wiki/Ratfor')
Language.create(name: 'rc', url:'http://en.wikipedia.org/wiki/Rc')
Language.create(name: 'REBOL', url:'http://en.wikipedia.org/wiki/REBOL')
Language.create(name: 'Red', url:'http://en.wikipedia.org/wiki/Red_(programming_language)')
Language.create(name: 'Redcode', url:'http://en.wikipedia.org/wiki/Core_War')
Language.create(name: 'REFAL', url:'http://en.wikipedia.org/wiki/REFAL')
Language.create(name: 'Reia', url:'http://en.wikipedia.org/wiki/Reia_(programming_language)')
Language.create(name: 'Revolution', url:'http://en.wikipedia.org/wiki/Revolution_(programming_language)')
Language.create(name: 'rex', url:'http://en.wikipedia.org/wiki/Rex_(language)')
Language.create(name: 'REXX', url:'http://en.wikipedia.org/wiki/REXX')
Language.create(name: 'Rlab', url:'http://en.wikipedia.org/wiki/Rlab')
Language.create(name: 'ROOP', url:'http://en.wikipedia.org/wiki/ROOP_(programming_language)')
Language.create(name: 'RPG', url:'http://en.wikipedia.org/wiki/IBM_RPG')
Language.create(name: 'RPL', url:'http://en.wikipedia.org/wiki/RPL_(programming_language)')
Language.create(name: 'RSL', url:'http://en.wikipedia.org/wiki/Robot_Battle#Robot_scripting_language')
Language.create(name: 'RTL/2', url:'http://en.wikipedia.org/wiki/RTL/2')
Language.create(name: 'Ruby', url:'http://en.wikipedia.org/wiki/Ruby_(programming_language)')
Language.create(name: 'RuneScript', url:'http://en.wikipedia.org/wiki/RuneScape#History_and_development')
Language.create(name: 'Rust', url:'http://en.wikipedia.org/wiki/Rust_(programming_language)')
Language.create(name: 'S', url:'http://en.wikipedia.org/wiki/S_(programming_language)')
Language.create(name: 'S2', url:'http://en.wikipedia.org/wiki/S2_(programming_language)')
Language.create(name: 'S3', url:'http://en.wikipedia.org/wiki/S3_(programming_language)')
Language.create(name: 'S-Lang', url:'http://en.wikipedia.org/wiki/S-Lang_(programming_language)')
Language.create(name: 'S-PLUS', url:'http://en.wikipedia.org/wiki/S-PLUS')
Language.create(name: 'SA-C', url:'http://en.wikipedia.org/wiki/SA-C_(programming_language)')
Language.create(name: 'SabreTalk', url:'http://en.wikipedia.org/wiki/SabreTalk')
Language.create(name: 'SAIL', url:'http://en.wikipedia.org/wiki/SAIL_(programming_language)')
Language.create(name: 'SALSA', url:'http://en.wikipedia.org/wiki/SALSA_(programming_language)')
Language.create(name: 'SAM76', url:'http://en.wikipedia.org/wiki/SAM76')
Language.create(name: 'SAS', url:'http://en.wikipedia.org/wiki/SAS_System')
Language.create(name: 'SASL', url:'http://en.wikipedia.org/wiki/SASL_(programming_language)')
Language.create(name: 'Sather', url:'http://en.wikipedia.org/wiki/Sather')
Language.create(name: 'Sawzall', url:'http://en.wikipedia.org/wiki/Sawzall_(programming_language)')
Language.create(name: 'SBL', url:'http://en.wikipedia.org/wiki/Superbase_database')
Language.create(name: 'Scala', url:'http://en.wikipedia.org/wiki/Scala_(programming_language)')
Language.create(name: 'Scheme', url:'http://en.wikipedia.org/wiki/Scheme_(programming_language)')
Language.create(name: 'Scilab', url:'http://en.wikipedia.org/wiki/Scilab')
Language.create(name: 'Scratch', url:'http://en.wikipedia.org/wiki/Scratch_(programming_language)')
Language.create(name: 'Script.NET', url:'http://en.wikipedia.org/wiki/Script.NET')
Language.create(name: 'Sed', url:'http://en.wikipedia.org/wiki/Sed')
Language.create(name: 'Seed7', url:'http://en.wikipedia.org/wiki/Seed7')
Language.create(name: 'Self', url:'http://en.wikipedia.org/wiki/Self_(programming_language)')
Language.create(name: 'SenseTalk', url:'http://en.wikipedia.org/wiki/SenseTalk')
Language.create(name: 'SequenceL', url:'http://en.wikipedia.org/wiki/SequenceL')
Language.create(name: 'SETL', url:'http://en.wikipedia.org/wiki/SETL')
Language.create(name: 'SIMPOL', url:'http://en.wikipedia.org/wiki/Superbase_database#History')
Language.create(name: 'SIGNAL', url:'http://en.wikipedia.org/wiki/SIGNAL_(programming_language)')
Language.create(name: 'SiMPLE', url:'http://en.wikipedia.org/wiki/SiMPLE')
Language.create(name: 'SIMSCRIPT', url:'http://en.wikipedia.org/wiki/SIMSCRIPT')
Language.create(name: 'Simula', url:'http://en.wikipedia.org/wiki/Simula')
Language.create(name: 'Simulink', url:'http://en.wikipedia.org/wiki/Simulink')
Language.create(name: 'SISAL', url:'http://en.wikipedia.org/wiki/SISAL')
Language.create(name: 'SLIP', url:'http://en.wikipedia.org/wiki/SLIP_(programming_language)')
Language.create(name: 'SMALL', url:'http://en.wikipedia.org/wiki/SMALL')
Language.create(name: 'Smalltalk', url:'http://en.wikipedia.org/wiki/Smalltalk')
Language.create(name: 'Small Basic', url:'http://en.wikipedia.org/wiki/Microsoft_Small_Basic')
Language.create(name: 'SML', url:'http://en.wikipedia.org/wiki/Standard_ML')
Language.create(name: 'Snap!', url:'http://en.wikipedia.org/wiki/Snap!_(programming_language)')
Language.create(name: 'SNOBOL', url:'http://en.wikipedia.org/wiki/SNOBOL')
Language.create(name: 'SPITBOL', url:'http://en.wikipedia.org/wiki/SPITBOL_compiler')
Language.create(name: 'Snowball', url:'http://en.wikipedia.org/wiki/Snowball_programming_language')
Language.create(name: 'SOL', url:'http://en.wikipedia.org/wiki/Secure_Operations_Language')
Language.create(name: 'Span', url:'http://en.wikipedia.org/wiki/Span_(programming_language)')
Language.create(name: 'SPARK', url:'http://en.wikipedia.org/wiki/SPARK_(programming_language)')
Language.create(name: 'Speedcode', url:'http://en.wikipedia.org/wiki/Speedcoding')
Language.create(name: 'SPIN', url:'http://en.wikipedia.org/wiki/Parallax_Propeller')
Language.create(name: 'SP/k', url:'http://en.wikipedia.org/wiki/SP/k')
Language.create(name: 'SPS', url:'http://en.wikipedia.org/wiki/IBM_1401_Symbolic_Programming_System')
Language.create(name: 'SQR', url:'http://en.wikipedia.org/wiki/SQR')
Language.create(name: 'Squeak', url:'http://en.wikipedia.org/wiki/Squeak')
Language.create(name: 'Squirrel', url:'http://en.wikipedia.org/wiki/Squirrel_(programming_language)')
Language.create(name: 'SR', url:'http://en.wikipedia.org/wiki/SR_(programming_language)')
Language.create(name: 'S/SL', url:'http://en.wikipedia.org/wiki/S/SL_programming_language')
Language.create(name: 'Stackless Python', url:'http://en.wikipedia.org/wiki/Stackless_Python')
Language.create(name: 'Starlogo', url:'http://en.wikipedia.org/wiki/Starlogo')
Language.create(name: 'Strand', url:'http://en.wikipedia.org/wiki/Strand_(programming_language)')
Language.create(name: 'Stata', url:'http://en.wikipedia.org/wiki/Stata')
Language.create(name: 'Stateflow', url:'http://en.wikipedia.org/wiki/Stateflow')
Language.create(name: 'Subtext', url:'http://en.wikipedia.org/wiki/Subtext_(programming_language)')
Language.create(name: 'SuperCollider', url:'http://en.wikipedia.org/wiki/SuperCollider')
Language.create(name: 'SuperTalk', url:'http://en.wikipedia.org/wiki/SuperTalk')
Language.create(name: 'Swift (Apple programming language)', url:'http://en.wikipedia.org/wiki/Swift_(programming_language)')
Language.create(name: 'Swift (parallel scripting language)', url:'http://en.wikipedia.org/wiki/Swift_(parallel_scripting_language)')
Language.create(name: 'SYMPL', url:'http://en.wikipedia.org/wiki/SYMPL')
Language.create(name: 'SyncCharts', url:'http://en.wikipedia.org/wiki/SyncCharts')
Language.create(name: 'SystemVerilog', url:'http://en.wikipedia.org/wiki/SystemVerilog')
Language.create(name: 'T', url:'http://en.wikipedia.org/wiki/T_(programming_language)')
Language.create(name: 'TACL', url:'http://en.wikipedia.org/wiki/TACL')
Language.create(name: 'TACPOL', url:'http://en.wikipedia.org/wiki/TACPOL_(programming_language)')
Language.create(name: 'TADS', url:'http://en.wikipedia.org/wiki/TADS')
Language.create(name: 'TAL', url:'http://en.wikipedia.org/wiki/Transaction_Application_Language')
Language.create(name: 'Tcl', url:'http://en.wikipedia.org/wiki/Tcl')
Language.create(name: 'Tea', url:'http://en.wikipedia.org/wiki/Tea_(programming_language)')
Language.create(name: 'TECO', url:'http://en.wikipedia.org/wiki/Text_Editor_and_Corrector')
Language.create(name: 'TELCOMP', url:'http://en.wikipedia.org/wiki/TELCOMP')
Language.create(name: 'TeX', url:'http://en.wikipedia.org/wiki/TeX')
Language.create(name: 'TEX', url:'http://en.wikipedia.org/wiki/Text_Executive_Programming_Language')
Language.create(name: 'TIE', url:'http://en.wikipedia.org/wiki/Tensilica_Instruction_Extension')
Language.create(name: 'Timber', url:'http://en.wikipedia.org/wiki/Timber_(programming_language)')
Language.create(name: 'TMG', url:'http://en.wikipedia.org/wiki/TMG_(language)')
Language.create(name: 'Tom', url:'http://en.wikipedia.org/wiki/Tom_(pattern_matching_language)')
Language.create(name: 'TOM', url:'http://en.wikipedia.org/wiki/TOM_(object-oriented_programming_language)')
Language.create(name: 'TouchDevelop', url:'http://en.wikipedia.org/wiki/TouchDevelop')
Language.create(name: 'Topspeed', url:'http://en.wikipedia.org/wiki/Clarion_(programming_language)')
Language.create(name: 'TPU', url:'http://en.wikipedia.org/wiki/Text_Processing_Utility')
Language.create(name: 'Trac', url:'http://en.wikipedia.org/wiki/TRAC_(programming_language)')
Language.create(name: 'TTM', url:'http://en.wikipedia.org/wiki/TTM_(programming_language)')
Language.create(name: 'T-SQL', url:'http://en.wikipedia.org/wiki/Transact-SQL')
Language.create(name: 'TTCN', url:'http://en.wikipedia.org/wiki/TTCN')
Language.create(name: 'Turing', url:'http://en.wikipedia.org/wiki/Turing_(programming_language)')
Language.create(name: 'TUTOR', url:'http://en.wikipedia.org/wiki/TUTOR_(programming_language)')
Language.create(name: 'TXL', url:'http://en.wikipedia.org/wiki/TXL_(programming_language)')
Language.create(name: 'TypeScript', url:'http://en.wikipedia.org/wiki/TypeScript')
Language.create(name: 'Turbo C++', url:'http://en.wikipedia.org/wiki/Turbo_C%2B%2B')
Language.create(name: 'Ubercode', url:'http://en.wikipedia.org/wiki/Ubercode')
Language.create(name: 'UCSD Pascal', url:'http://en.wikipedia.org/wiki/UCSD_Pascal')
Language.create(name: 'Umple', url:'http://en.wikipedia.org/wiki/Umple')
Language.create(name: 'Unicon', url:'http://en.wikipedia.org/wiki/Unicon_(programming_language)')
Language.create(name: 'Uniface', url:'http://en.wikipedia.org/wiki/Uniface_(programming_language)')
Language.create(name: 'UNITY', url:'http://en.wikipedia.org/wiki/UNITY_(programming_language)')
Language.create(name: 'Unix shell', url:'http://en.wikipedia.org/wiki/Unix_shell')
Language.create(name: 'UnrealScript', url:'http://en.wikipedia.org/wiki/UnrealScript')
Language.create(name: 'Vala', url:'http://en.wikipedia.org/wiki/Vala_(programming_language)')
Language.create(name: 'VBA', url:'http://en.wikipedia.org/wiki/Visual_Basic_for_Applications')
Language.create(name: 'VBScript', url:'http://en.wikipedia.org/wiki/VBScript')
Language.create(name: 'Verilog', url:'http://en.wikipedia.org/wiki/Verilog')
Language.create(name: 'VHDL', url:'http://en.wikipedia.org/wiki/VHDL')
Language.create(name: 'Visual Basic', url:'http://en.wikipedia.org/wiki/Visual_Basic')
Language.create(name: 'Visual Basic .NET', url:'http://en.wikipedia.org/wiki/Visual_Basic_.NET')
Language.create(name: 'Visual DataFlex', url:'http://en.wikipedia.org/wiki/Visual_DataFlex')
Language.create(name: 'Visual DialogScript', url:'http://en.wikipedia.org/wiki/Visual_DialogScript')
Language.create(name: 'Visual Fortran', url:'http://en.wikipedia.org/wiki/Visual_Fortran')
Language.create(name: 'Visual FoxPro', url:'http://en.wikipedia.org/wiki/Visual_FoxPro')
Language.create(name: 'Visual J++', url:'http://en.wikipedia.org/wiki/Visual_J%2B%2B')
Language.create(name: 'Visual J#', url:'http://en.wikipedia.org/wiki/Visual_J')
Language.create(name: 'Visual Objects', url:'http://en.wikipedia.org/wiki/Visual_Objects')
Language.create(name: 'Visual Prolog', url:'http://en.wikipedia.org/wiki/Visual_Prolog')
Language.create(name: 'VSXu', url:'http://en.wikipedia.org/wiki/VSXu')
Language.create(name: 'vvvv', url:'http://en.wikipedia.org/wiki/Vvvv')
Language.create(name: 'WATFIV, WATFOR', url:'http://en.wikipedia.org/wiki/WATFIV_(programming_language)')
Language.create(name: 'WebDNA', url:'http://en.wikipedia.org/wiki/WebDNA')
Language.create(name: 'WebQL', url:'http://en.wikipedia.org/wiki/WebQL')
Language.create(name: 'Windows PowerShell', url:'http://en.wikipedia.org/wiki/Windows_PowerShell')
Language.create(name: 'Winbatch', url:'http://en.wikipedia.org/wiki/Winbatch')
Language.create(name: 'Wolfram Language', url:'http://en.wikipedia.org/wiki/Wolfram_Language')
Language.create(name: 'Wyvern', url:'http://en.wikipedia.org/wiki/Wyvern_(programming_language)')
Language.create(name: 'X++', url:'http://en.wikipedia.org/wiki/Microsoft_Dynamics_AX')
Language.create(name: 'X#', url:'http://en.wikipedia.org/wiki/X_Sharp_(programming_language)')
Language.create(name: 'X10', url:'http://en.wikipedia.org/wiki/X10_(programming_language)')
Language.create(name: 'XBL', url:'http://en.wikipedia.org/wiki/XBL')
Language.create(name: 'XC', url:'http://en.wikipedia.org/wiki/XC_Programming_Language')
Language.create(name: 'XMOS architecture', url:'http://en.wikipedia.org/wiki/XCore_XS1')
Language.create(name: 'xHarbour', url:'http://en.wikipedia.org/wiki/XHarbour')
Language.create(name: 'XL', url:'http://en.wikipedia.org/wiki/XL_(programming_language)')
Language.create(name: 'Xojo', url:'http://en.wikipedia.org/wiki/Xojo')
Language.create(name: 'XOTcl', url:'http://en.wikipedia.org/wiki/XOTcl')
Language.create(name: 'XPL', url:'http://en.wikipedia.org/wiki/XPL')
Language.create(name: 'XPL0', url:'http://en.wikipedia.org/wiki/XPL0')
Language.create(name: 'XQuery', url:'http://en.wikipedia.org/wiki/XQuery')
Language.create(name: 'XSB', url:'http://en.wikipedia.org/wiki/XSB')
Language.create(name: 'XSLT', url:'http://en.wikipedia.org/wiki/XSL_Transformations')
Language.create(name: 'XPath', url:'http://en.wikipedia.org/wiki/XPath')
Language.create(name: 'Xtend', url:'http://en.wikipedia.org/wiki/Xtend')
Language.create(name: 'Yorick', url:'http://en.wikipedia.org/wiki/Yorick_(programming_language)')
Language.create(name: 'YQL', url:'http://en.wikipedia.org/wiki/YQL_(programming_language)')
Language.create(name: 'Z notation', url:'http://en.wikipedia.org/wiki/Z_notation')
Language.create(name: 'Zeno', url:'http://en.wikipedia.org/wiki/Zeno_(programming_language)')
Language.create(name: 'ZOPL', url:'http://en.wikipedia.org/wiki/ZOPL')
Language.create(name: 'ZPL', url:'http://en.wikipedia.org/wiki/ZPL_(programming_language)')
